# Generated by Django 4.1 on 2022-11-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_brand_en_product_brand_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_fr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor_fr',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
