# Generated by Django 4.1 on 2022-11-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Subscribers',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
